interface songInterface {
	title: string
	lyrics: string[]
	songLanguage: "en" | "ru"
	timings: number[]
	intro: number
	end: number
	typeOfSong:
		| "rap"
		| "hiphop"
		| "rock"
		| "electric"
		| "R&B"
		| "Latin"
		| "Country"
		| "Jazz"
		| "K-pop"
		| "Reggie"
	complexity: "HARD" | "EASY" | "NORMAL"
	author: string
	image: string
	id: string
}
type songs = Array<songInterface>
export const biggerThanEverythingYeat: songInterface = {
	author: "Yeat",
	title: "Bigger than everything",
	intro: 19,
	lyrics: [
		"Now this shit got big this shit got bigger than ever",
		"I just hopped the jet this shit go straight to LA",
		"Bitch I done got rich I done got richer than ever",
		"Now I got these whips these whips bigger than ever",
		"I been blocking shade I sit under umbrellas",
		"I'm an alien bitch I feel like changing the weather",
		"I don't even talk to nobody no bitch but it's smooth like butter",
		"I been chilling out lil' bitch but I'm high as them devils",
		"We so mad like devils in our head",
		"I'm on demand every time I drop I am",
		"We so mad them devils call me 'Him'",
		"They call me God 'cause I'm as high as Him",
		"I remember back when I was fucking broke",
		"Now I'm chilling out in south of France on a boat",
		"I could make the money come I can make it go",
		"I don't need to fly I just need to flow",
		"I don't even laugh y'all already jokes",
		"All my money flip all my money bloats",
		"All my diamonds shine all my diamonds moats",
		"I might have to go lose control",
		"I got diamonds on my yacht and I got diamonds on my bitch",
		"I could put money on your heads I could put money on your kids",
		"I call the mob and they come kill 'em that's as easy as it gets",
		"I'm done laying back plotting I'm dropping everything I'm dropping all these hits",
		"It take a lot of motherfucking money just to get here and look like this",
		"I had to shit on them constantly so they could look at me and fear for they life",
		"Way back when them thoughts was easy",
		"Now shit get sleazy and it get peezy",
		"I rock APeezy it get fleezy",
		"My diamonds 3D they're not CGI",
		"I can get you dead I can get you fried",
		"I can kill you with no eyes open",
		"They could cut out one of my eyes",
		"Why? Every time I look back they surprised",
		"Now this shit got big this shit got bigger than ever",
		"I just hopped the jet this shit go straight to LA",
		"Bitch I done got rich I done got richer than ever",
		"Now I got these whips these whips bigger than ever",
		"I been blocking shade I sit under umbrellas",
		"I'm an alien bitch I feel like changing the weather",
		"I don't even talk to nobody no bitch but it's smooth like butter",
		"I been chilling out lil' bitch but I'm high as them devils",
		"We so mad like devils in our head",
		"I'm on demand every time I drop I am",
		"We so mad them devils call me 'Him'",
		"They call me God 'cause I'm as high as Him",
		"I remember back when I was fucking broke",
		"Now I'm chilling out in south of France on a boat",
		"I could make the money come I can make it go",
		"I don't need to fly I just need to flow",
		"I don't even laugh y'all already jokes",
		"All my money flip all my money bloats",
		"All my diamonds shine all my diamonds moats",
		"I might have to go lose control",
	],
	songLanguage: "en",
	timings: [
		22, 25, 29, 32, 35, 38, 41, 44, 48, 51, 54, 58, 61, 64, 68, 71, 74, 78, 81,
		84, 90, 96, 103, 109, 114, 122, 125, 128, 131, 135, 138, 142, 144, 147, 150,
		153, 157, 160, 163, 166, 169, 172, 175, 179, 182, 186, 189, 192, 195, 198,
		202, 206, 209,
	],
	end: 248,
	typeOfSong: "rap",
	complexity: "HARD",
	image:
		"https://upload.wikimedia.org/wikipedia/en/c/c4/Yeat_-_Bigger_Then_Everything.jpg",
	id: "47832fdkjsdjf10239",
}

export const songsList: songs = [
	{
		author: "Yeat",
		title: "Bigger than everything",
		intro: 19,
		lyrics: [
			"Now this shit got big this shit got bigger than ever",
			"I just hopped the jet this shit go straight to LA",
			"Bitch I done got rich I done got richer than ever",
			"Now I got these whips these whips bigger than ever",
			"I been blocking shade I sit under umbrellas",
			"I'm an alien bitch I feel like changing the weather",
			"I don't even talk to nobody no bitch but it's smooth like butter",
			"I been chilling out lil' bitch but I'm high as them devils",
			"We so mad like devils in our head",
			"I'm on demand every time I drop I am",
			"We so mad them devils call me 'Him'",
			"They call me God 'cause I'm as high as Him",
			"I remember back when I was fucking broke",
			"Now I'm chilling out in south of France on a boat",
			"I could make the money come I can make it go",
			"I don't need to fly I just need to flow",
			"I don't even laugh y'all already jokes",
			"All my money flip all my money bloats",
			"All my diamonds shine all my diamonds moats",
			"I might have to go lose control",
			"I got diamonds on my yacht and I got diamonds on my bitch",
			"I could put money on your heads I could put money on your kids",
			"I call the mob and they come kill 'em that's as easy as it gets",
			"I'm done laying back plotting I'm dropping everything I'm dropping all these hits",
			"It take a lot of motherfucking money just to get here and look like this",
			"I had to shit on them constantly so they could look at me and fear for they life",
			"Way back when them thoughts was easy",
			"Now shit get sleazy and it get peezy",
			"I rock APeezy it get fleezy",
			"My diamonds 3D they're not CGI",
			"I can get you dead I can get you fried",
			"I can kill you with no eyes open",
			"They could cut out one of my eyes",
			"Why? Every time I look back they surprised",
			"Now this shit got big this shit got bigger than ever",
			"I just hopped the jet this shit go straight to LA",
			"Bitch I done got rich I done got richer than ever",
			"Now I got these whips these whips bigger than ever",
			"I been blocking shade I sit under umbrellas",
			"I'm an alien bitch I feel like changing the weather",
			"I don't even talk to nobody no bitch but it's smooth like butter",
			"I been chilling out lil' bitch but I'm high as them devils",
			"We so mad like devils in our head",
			"I'm on demand every time I drop I am",
			"We so mad them devils call me 'Him'",
			"They call me God 'cause I'm as high as Him",
			"I remember back when I was fucking broke",
			"Now I'm chilling out in south of France on a boat",
			"I could make the money come I can make it go",
			"I don't need to fly I just need to flow",
			"I don't even laugh y'all already jokes",
			"All my money flip all my money bloats",
			"All my diamonds shine all my diamonds moats",
			"I might have to go lose control",
		],
		songLanguage: "en",
		timings: [
			22, 25, 29, 32, 35, 38, 41, 44, 48, 51, 54, 58, 61, 64, 68, 71, 74, 78,
			81, 84, 90, 96, 103, 109, 114, 122, 125, 128, 131, 135, 138, 142, 144,
			147, 150, 153, 157, 160, 163, 166, 169, 172, 175, 179, 182, 186, 189, 192,
			195, 198, 202, 206, 209,
		],
		end: 248,
		typeOfSong: "rap",
		complexity: "HARD",
		image:
			"https://upload.wikimedia.org/wikipedia/en/c/c4/Yeat_-_Bigger_Then_Everything.jpg",
		id: "47832fdkjsdjf10239",
	},
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	biggerThanEverythingYeat,
	{
		author: "Yeat",
		title: "Bigger than everything",
		intro: 19,
		lyrics: [
			"Now this shit got big this shit got bigger than ever",
			"I just hopped the jet this shit go straight to LA",
			"Bitch I done got rich I done got richer than ever",
			"Now I got these whips these whips bigger than ever",
			"I been blocking shade I sit under umbrellas",
			"I'm an alien bitch I feel like changing the weather",
			"I don't even talk to nobody no bitch but it's smooth like butter",
			"I been chilling out lil' bitch but I'm high as them devils",
			"We so mad like devils in our head",
			"I'm on demand every time I drop I am",
			"We so mad them devils call me 'Him'",
			"They call me God 'cause I'm as high as Him",
			"I remember back when I was fucking broke",
			"Now I'm chilling out in south of France on a boat",
			"I could make the money come I can make it go",
			"I don't need to fly I just need to flow",
			"I don't even laugh y'all already jokes",
			"All my money flip all my money bloats",
			"All my diamonds shine all my diamonds moats",
			"I might have to go lose control",
			"I got diamonds on my yacht and I got diamonds on my bitch",
			"I could put money on your heads I could put money on your kids",
			"I call the mob and they come kill 'em that's as easy as it gets",
			"I'm done laying back plotting I'm dropping everything I'm dropping all these hits",
			"It take a lot of motherfucking money just to get here and look like this",
			"I had to shit on them constantly so they could look at me and fear for they life",
			"Way back when them thoughts was easy",
			"Now shit get sleazy and it get peezy",
			"I rock APeezy it get fleezy",
			"My diamonds 3D they're not CGI",
			"I can get you dead I can get you fried",
			"I can kill you with no eyes open",
			"They could cut out one of my eyes",
			"Why? Every time I look back they surprised",
			"Now this shit got big this shit got bigger than ever",
			"I just hopped the jet this shit go straight to LA",
			"Bitch I done got rich I done got richer than ever",
			"Now I got these whips these whips bigger than ever",
			"I been blocking shade I sit under umbrellas",
			"I'm an alien bitch I feel like changing the weather",
			"I don't even talk to nobody no bitch but it's smooth like butter",
			"I been chilling out lil' bitch but I'm high as them devils",
			"We so mad like devils in our head",
			"I'm on demand every time I drop I am",
			"We so mad them devils call me 'Him'",
			"They call me God 'cause I'm as high as Him",
			"I remember back when I was fucking broke",
			"Now I'm chilling out in south of France on a boat",
			"I could make the money come I can make it go",
			"I don't need to fly I just need to flow",
			"I don't even laugh y'all already jokes",
			"All my money flip all my money bloats",
			"All my diamonds shine all my diamonds moats",
			"I might have to go lose control",
		],
		songLanguage: "en",
		timings: [
			22, 25, 29, 32, 35, 38, 41, 44, 48, 51, 54, 58, 61, 64, 68, 71, 74, 78,
			81, 84, 90, 96, 103, 109, 114, 122, 125, 128, 131, 135, 138, 142, 144,
			147, 150, 153, 157, 160, 163, 166, 169, 172, 175, 179, 182, 186, 189, 192,
			195, 198, 202, 206, 209,
		],
		end: 248,
		typeOfSong: "hiphop",
		complexity: "EASY",
		image:
			"https://upload.wikimedia.org/wikipedia/en/c/c4/Yeat_-_Bigger_Then_Everything.jpg",
		id: "47832fdkjsdjf10239",
	},
	{
		author: "Yeat",
		title: "Bigger than everything",
		intro: 19,
		lyrics: [
			"Now this shit got big this shit got bigger than ever",
			"I just hopped the jet this shit go straight to LA",
			"Bitch I done got rich I done got richer than ever",
			"Now I got these whips these whips bigger than ever",
			"I been blocking shade I sit under umbrellas",
			"I'm an alien bitch I feel like changing the weather",
			"I don't even talk to nobody no bitch but it's smooth like butter",
			"I been chilling out lil' bitch but I'm high as them devils",
			"We so mad like devils in our head",
			"I'm on demand every time I drop I am",
			"We so mad them devils call me 'Him'",
			"They call me God 'cause I'm as high as Him",
			"I remember back when I was fucking broke",
			"Now I'm chilling out in south of France on a boat",
			"I could make the money come I can make it go",
			"I don't need to fly I just need to flow",
			"I don't even laugh y'all already jokes",
			"All my money flip all my money bloats",
			"All my diamonds shine all my diamonds moats",
			"I might have to go lose control",
			"I got diamonds on my yacht and I got diamonds on my bitch",
			"I could put money on your heads I could put money on your kids",
			"I call the mob and they come kill 'em that's as easy as it gets",
			"I'm done laying back plotting I'm dropping everything I'm dropping all these hits",
			"It take a lot of motherfucking money just to get here and look like this",
			"I had to shit on them constantly so they could look at me and fear for they life",
			"Way back when them thoughts was easy",
			"Now shit get sleazy and it get peezy",
			"I rock APeezy it get fleezy",
			"My diamonds 3D they're not CGI",
			"I can get you dead I can get you fried",
			"I can kill you with no eyes open",
			"They could cut out one of my eyes",
			"Why? Every time I look back they surprised",
			"Now this shit got big this shit got bigger than ever",
			"I just hopped the jet this shit go straight to LA",
			"Bitch I done got rich I done got richer than ever",
			"Now I got these whips these whips bigger than ever",
			"I been blocking shade I sit under umbrellas",
			"I'm an alien bitch I feel like changing the weather",
			"I don't even talk to nobody no bitch but it's smooth like butter",
			"I been chilling out lil' bitch but I'm high as them devils",
			"We so mad like devils in our head",
			"I'm on demand every time I drop I am",
			"We so mad them devils call me 'Him'",
			"They call me God 'cause I'm as high as Him",
			"I remember back when I was fucking broke",
			"Now I'm chilling out in south of France on a boat",
			"I could make the money come I can make it go",
			"I don't need to fly I just need to flow",
			"I don't even laugh y'all already jokes",
			"All my money flip all my money bloats",
			"All my diamonds shine all my diamonds moats",
			"I might have to go lose control",
		],
		songLanguage: "en",
		timings: [
			22, 25, 29, 32, 35, 38, 41, 44, 48, 51, 54, 58, 61, 64, 68, 71, 74, 78,
			81, 84, 90, 96, 103, 109, 114, 122, 125, 128, 131, 135, 138, 142, 144,
			147, 150, 153, 157, 160, 163, 166, 169, 172, 175, 179, 182, 186, 189, 192,
			195, 198, 202, 206, 209,
		],
		end: 248,
		typeOfSong: "rock",
		complexity: "HARD",
		image:
			"https://upload.wikimedia.org/wikipedia/en/c/c4/Yeat_-_Bigger_Then_Everything.jpg",
		id: "47832fdkjsdjf10239",
	},
	{
		author: "Yeat",
		title: "Bigger than everything",
		intro: 19,
		lyrics: [
			"Now this shit got big this shit got bigger than ever",
			"I just hopped the jet this shit go straight to LA",
			"Bitch I done got rich I done got richer than ever",
			"Now I got these whips these whips bigger than ever",
			"I been blocking shade I sit under umbrellas",
			"I'm an alien bitch I feel like changing the weather",
			"I don't even talk to nobody no bitch but it's smooth like butter",
			"I been chilling out lil' bitch but I'm high as them devils",
			"We so mad like devils in our head",
			"I'm on demand every time I drop I am",
			"We so mad them devils call me 'Him'",
			"They call me God 'cause I'm as high as Him",
			"I remember back when I was fucking broke",
			"Now I'm chilling out in south of France on a boat",
			"I could make the money come I can make it go",
			"I don't need to fly I just need to flow",
			"I don't even laugh y'all already jokes",
			"All my money flip all my money bloats",
			"All my diamonds shine all my diamonds moats",
			"I might have to go lose control",
			"I got diamonds on my yacht and I got diamonds on my bitch",
			"I could put money on your heads I could put money on your kids",
			"I call the mob and they come kill 'em that's as easy as it gets",
			"I'm done laying back plotting I'm dropping everything I'm dropping all these hits",
			"It take a lot of motherfucking money just to get here and look like this",
			"I had to shit on them constantly so they could look at me and fear for they life",
			"Way back when them thoughts was easy",
			"Now shit get sleazy and it get peezy",
			"I rock APeezy it get fleezy",
			"My diamonds 3D they're not CGI",
			"I can get you dead I can get you fried",
			"I can kill you with no eyes open",
			"They could cut out one of my eyes",
			"Why? Every time I look back they surprised",
			"Now this shit got big this shit got bigger than ever",
			"I just hopped the jet this shit go straight to LA",
			"Bitch I done got rich I done got richer than ever",
			"Now I got these whips these whips bigger than ever",
			"I been blocking shade I sit under umbrellas",
			"I'm an alien bitch I feel like changing the weather",
			"I don't even talk to nobody no bitch but it's smooth like butter",
			"I been chilling out lil' bitch but I'm high as them devils",
			"We so mad like devils in our head",
			"I'm on demand every time I drop I am",
			"We so mad them devils call me 'Him'",
			"They call me God 'cause I'm as high as Him",
			"I remember back when I was fucking broke",
			"Now I'm chilling out in south of France on a boat",
			"I could make the money come I can make it go",
			"I don't need to fly I just need to flow",
			"I don't even laugh y'all already jokes",
			"All my money flip all my money bloats",
			"All my diamonds shine all my diamonds moats",
			"I might have to go lose control",
		],
		songLanguage: "en",
		timings: [
			22, 25, 29, 32, 35, 38, 41, 44, 48, 51, 54, 58, 61, 64, 68, 71, 74, 78,
			81, 84, 90, 96, 103, 109, 114, 122, 125, 128, 131, 135, 138, 142, 144,
			147, 150, 153, 157, 160, 163, 166, 169, 172, 175, 179, 182, 186, 189, 192,
			195, 198, 202, 206, 209,
		],
		end: 248,
		typeOfSong: "electric",
		complexity: "HARD",
		image:
			"https://upload.wikimedia.org/wikipedia/en/c/c4/Yeat_-_Bigger_Then_Everything.jpg",
		id: "47832fdkjsdjf10239",
	},
	{
		author: "Yeat",
		title: "Bigger than everything",
		intro: 19,
		lyrics: [
			"Now this shit got big this shit got bigger than ever",
			"I just hopped the jet this shit go straight to LA",
			"Bitch I done got rich I done got richer than ever",
			"Now I got these whips these whips bigger than ever",
			"I been blocking shade I sit under umbrellas",
			"I'm an alien bitch I feel like changing the weather",
			"I don't even talk to nobody no bitch but it's smooth like butter",
			"I been chilling out lil' bitch but I'm high as them devils",
			"We so mad like devils in our head",
			"I'm on demand every time I drop I am",
			"We so mad them devils call me 'Him'",
			"They call me God 'cause I'm as high as Him",
			"I remember back when I was fucking broke",
			"Now I'm chilling out in south of France on a boat",
			"I could make the money come I can make it go",
			"I don't need to fly I just need to flow",
			"I don't even laugh y'all already jokes",
			"All my money flip all my money bloats",
			"All my diamonds shine all my diamonds moats",
			"I might have to go lose control",
			"I got diamonds on my yacht and I got diamonds on my bitch",
			"I could put money on your heads I could put money on your kids",
			"I call the mob and they come kill 'em that's as easy as it gets",
			"I'm done laying back plotting I'm dropping everything I'm dropping all these hits",
			"It take a lot of motherfucking money just to get here and look like this",
			"I had to shit on them constantly so they could look at me and fear for they life",
			"Way back when them thoughts was easy",
			"Now shit get sleazy and it get peezy",
			"I rock APeezy it get fleezy",
			"My diamonds 3D they're not CGI",
			"I can get you dead I can get you fried",
			"I can kill you with no eyes open",
			"They could cut out one of my eyes",
			"Why? Every time I look back they surprised",
			"Now this shit got big this shit got bigger than ever",
			"I just hopped the jet this shit go straight to LA",
			"Bitch I done got rich I done got richer than ever",
			"Now I got these whips these whips bigger than ever",
			"I been blocking shade I sit under umbrellas",
			"I'm an alien bitch I feel like changing the weather",
			"I don't even talk to nobody no bitch but it's smooth like butter",
			"I been chilling out lil' bitch but I'm high as them devils",
			"We so mad like devils in our head",
			"I'm on demand every time I drop I am",
			"We so mad them devils call me 'Him'",
			"They call me God 'cause I'm as high as Him",
			"I remember back when I was fucking broke",
			"Now I'm chilling out in south of France on a boat",
			"I could make the money come I can make it go",
			"I don't need to fly I just need to flow",
			"I don't even laugh y'all already jokes",
			"All my money flip all my money bloats",
			"All my diamonds shine all my diamonds moats",
			"I might have to go lose control",
		],
		songLanguage: "en",
		timings: [
			22, 25, 29, 32, 35, 38, 41, 44, 48, 51, 54, 58, 61, 64, 68, 71, 74, 78,
			81, 84, 90, 96, 103, 109, 114, 122, 125, 128, 131, 135, 138, 142, 144,
			147, 150, 153, 157, 160, 163, 166, 169, 172, 175, 179, 182, 186, 189, 192,
			195, 198, 202, 206, 209,
		],
		end: 248,
		typeOfSong: "R&B",
		complexity: "HARD",
		image:
			"https://upload.wikimedia.org/wikipedia/en/c/c4/Yeat_-_Bigger_Then_Everything.jpg",
		id: "47832fdkjsdjf10239",
	},
	{
		author: "Yeat",
		title: "Bigger than everything",
		intro: 19,
		lyrics: [
			"Now this shit got big this shit got bigger than ever",
			"I just hopped the jet this shit go straight to LA",
			"Bitch I done got rich I done got richer than ever",
			"Now I got these whips these whips bigger than ever",
			"I been blocking shade I sit under umbrellas",
			"I'm an alien bitch I feel like changing the weather",
			"I don't even talk to nobody no bitch but it's smooth like butter",
			"I been chilling out lil' bitch but I'm high as them devils",
			"We so mad like devils in our head",
			"I'm on demand every time I drop I am",
			"We so mad them devils call me 'Him'",
			"They call me God 'cause I'm as high as Him",
			"I remember back when I was fucking broke",
			"Now I'm chilling out in south of France on a boat",
			"I could make the money come I can make it go",
			"I don't need to fly I just need to flow",
			"I don't even laugh y'all already jokes",
			"All my money flip all my money bloats",
			"All my diamonds shine all my diamonds moats",
			"I might have to go lose control",
			"I got diamonds on my yacht and I got diamonds on my bitch",
			"I could put money on your heads I could put money on your kids",
			"I call the mob and they come kill 'em that's as easy as it gets",
			"I'm done laying back plotting I'm dropping everything I'm dropping all these hits",
			"It take a lot of motherfucking money just to get here and look like this",
			"I had to shit on them constantly so they could look at me and fear for they life",
			"Way back when them thoughts was easy",
			"Now shit get sleazy and it get peezy",
			"I rock APeezy it get fleezy",
			"My diamonds 3D they're not CGI",
			"I can get you dead I can get you fried",
			"I can kill you with no eyes open",
			"They could cut out one of my eyes",
			"Why? Every time I look back they surprised",
			"Now this shit got big this shit got bigger than ever",
			"I just hopped the jet this shit go straight to LA",
			"Bitch I done got rich I done got richer than ever",
			"Now I got these whips these whips bigger than ever",
			"I been blocking shade I sit under umbrellas",
			"I'm an alien bitch I feel like changing the weather",
			"I don't even talk to nobody no bitch but it's smooth like butter",
			"I been chilling out lil' bitch but I'm high as them devils",
			"We so mad like devils in our head",
			"I'm on demand every time I drop I am",
			"We so mad them devils call me 'Him'",
			"They call me God 'cause I'm as high as Him",
			"I remember back when I was fucking broke",
			"Now I'm chilling out in south of France on a boat",
			"I could make the money come I can make it go",
			"I don't need to fly I just need to flow",
			"I don't even laugh y'all already jokes",
			"All my money flip all my money bloats",
			"All my diamonds shine all my diamonds moats",
			"I might have to go lose control",
		],
		songLanguage: "en",
		timings: [
			22, 25, 29, 32, 35, 38, 41, 44, 48, 51, 54, 58, 61, 64, 68, 71, 74, 78,
			81, 84, 90, 96, 103, 109, 114, 122, 125, 128, 131, 135, 138, 142, 144,
			147, 150, 153, 157, 160, 163, 166, 169, 172, 175, 179, 182, 186, 189, 192,
			195, 198, 202, 206, 209,
		],
		end: 248,
		typeOfSong: "Latin",
		complexity: "HARD",
		image:
			"https://upload.wikimedia.org/wikipedia/en/c/c4/Yeat_-_Bigger_Then_Everything.jpg",
		id: "47832fdkjsdjf10239",
	},
	{
		author: "Yeat",
		title: "Bigger than everything",
		intro: 19,
		lyrics: [
			"Now this shit got big this shit got bigger than ever",
			"I just hopped the jet this shit go straight to LA",
			"Bitch I done got rich I done got richer than ever",
			"Now I got these whips these whips bigger than ever",
			"I been blocking shade I sit under umbrellas",
			"I'm an alien bitch I feel like changing the weather",
			"I don't even talk to nobody no bitch but it's smooth like butter",
			"I been chilling out lil' bitch but I'm high as them devils",
			"We so mad like devils in our head",
			"I'm on demand every time I drop I am",
			"We so mad them devils call me 'Him'",
			"They call me God 'cause I'm as high as Him",
			"I remember back when I was fucking broke",
			"Now I'm chilling out in south of France on a boat",
			"I could make the money come I can make it go",
			"I don't need to fly I just need to flow",
			"I don't even laugh y'all already jokes",
			"All my money flip all my money bloats",
			"All my diamonds shine all my diamonds moats",
			"I might have to go lose control",
			"I got diamonds on my yacht and I got diamonds on my bitch",
			"I could put money on your heads I could put money on your kids",
			"I call the mob and they come kill 'em that's as easy as it gets",
			"I'm done laying back plotting I'm dropping everything I'm dropping all these hits",
			"It take a lot of motherfucking money just to get here and look like this",
			"I had to shit on them constantly so they could look at me and fear for they life",
			"Way back when them thoughts was easy",
			"Now shit get sleazy and it get peezy",
			"I rock APeezy it get fleezy",
			"My diamonds 3D they're not CGI",
			"I can get you dead I can get you fried",
			"I can kill you with no eyes open",
			"They could cut out one of my eyes",
			"Why? Every time I look back they surprised",
			"Now this shit got big this shit got bigger than ever",
			"I just hopped the jet this shit go straight to LA",
			"Bitch I done got rich I done got richer than ever",
			"Now I got these whips these whips bigger than ever",
			"I been blocking shade I sit under umbrellas",
			"I'm an alien bitch I feel like changing the weather",
			"I don't even talk to nobody no bitch but it's smooth like butter",
			"I been chilling out lil' bitch but I'm high as them devils",
			"We so mad like devils in our head",
			"I'm on demand every time I drop I am",
			"We so mad them devils call me 'Him'",
			"They call me God 'cause I'm as high as Him",
			"I remember back when I was fucking broke",
			"Now I'm chilling out in south of France on a boat",
			"I could make the money come I can make it go",
			"I don't need to fly I just need to flow",
			"I don't even laugh y'all already jokes",
			"All my money flip all my money bloats",
			"All my diamonds shine all my diamonds moats",
			"I might have to go lose control",
		],
		songLanguage: "en",
		timings: [
			22, 25, 29, 32, 35, 38, 41, 44, 48, 51, 54, 58, 61, 64, 68, 71, 74, 78,
			81, 84, 90, 96, 103, 109, 114, 122, 125, 128, 131, 135, 138, 142, 144,
			147, 150, 153, 157, 160, 163, 166, 169, 172, 175, 179, 182, 186, 189, 192,
			195, 198, 202, 206, 209,
		],
		end: 248,
		typeOfSong: "Country",
		complexity: "HARD",
		image:
			"https://upload.wikimedia.org/wikipedia/en/c/c4/Yeat_-_Bigger_Then_Everything.jpg",
		id: "47832fdkjsdjf10239",
	},
	{
		author: "Yeat",
		title: "Bigger than everything",
		intro: 19,
		lyrics: [
			"Now this shit got big this shit got bigger than ever",
			"I just hopped the jet this shit go straight to LA",
			"Bitch I done got rich I done got richer than ever",
			"Now I got these whips these whips bigger than ever",
			"I been blocking shade I sit under umbrellas",
			"I'm an alien bitch I feel like changing the weather",
			"I don't even talk to nobody no bitch but it's smooth like butter",
			"I been chilling out lil' bitch but I'm high as them devils",
			"We so mad like devils in our head",
			"I'm on demand every time I drop I am",
			"We so mad them devils call me 'Him'",
			"They call me God 'cause I'm as high as Him",
			"I remember back when I was fucking broke",
			"Now I'm chilling out in south of France on a boat",
			"I could make the money come I can make it go",
			"I don't need to fly I just need to flow",
			"I don't even laugh y'all already jokes",
			"All my money flip all my money bloats",
			"All my diamonds shine all my diamonds moats",
			"I might have to go lose control",
			"I got diamonds on my yacht and I got diamonds on my bitch",
			"I could put money on your heads I could put money on your kids",
			"I call the mob and they come kill 'em that's as easy as it gets",
			"I'm done laying back plotting I'm dropping everything I'm dropping all these hits",
			"It take a lot of motherfucking money just to get here and look like this",
			"I had to shit on them constantly so they could look at me and fear for they life",
			"Way back when them thoughts was easy",
			"Now shit get sleazy and it get peezy",
			"I rock APeezy it get fleezy",
			"My diamonds 3D they're not CGI",
			"I can get you dead I can get you fried",
			"I can kill you with no eyes open",
			"They could cut out one of my eyes",
			"Why? Every time I look back they surprised",
			"Now this shit got big this shit got bigger than ever",
			"I just hopped the jet this shit go straight to LA",
			"Bitch I done got rich I done got richer than ever",
			"Now I got these whips these whips bigger than ever",
			"I been blocking shade I sit under umbrellas",
			"I'm an alien bitch I feel like changing the weather",
			"I don't even talk to nobody no bitch but it's smooth like butter",
			"I been chilling out lil' bitch but I'm high as them devils",
			"We so mad like devils in our head",
			"I'm on demand every time I drop I am",
			"We so mad them devils call me 'Him'",
			"They call me God 'cause I'm as high as Him",
			"I remember back when I was fucking broke",
			"Now I'm chilling out in south of France on a boat",
			"I could make the money come I can make it go",
			"I don't need to fly I just need to flow",
			"I don't even laugh y'all already jokes",
			"All my money flip all my money bloats",
			"All my diamonds shine all my diamonds moats",
			"I might have to go lose control",
		],
		songLanguage: "en",
		timings: [
			22, 25, 29, 32, 35, 38, 41, 44, 48, 51, 54, 58, 61, 64, 68, 71, 74, 78,
			81, 84, 90, 96, 103, 109, 114, 122, 125, 128, 131, 135, 138, 142, 144,
			147, 150, 153, 157, 160, 163, 166, 169, 172, 175, 179, 182, 186, 189, 192,
			195, 198, 202, 206, 209,
		],
		end: 248,
		typeOfSong: "Jazz",
		complexity: "HARD",
		image:
			"https://upload.wikimedia.org/wikipedia/en/c/c4/Yeat_-_Bigger_Then_Everything.jpg",
		id: "47832fdkjsdjf10239",
	},
	{
		author: "Yeat",
		title: "Bigger than everything",
		intro: 19,
		lyrics: [
			"Now this shit got big this shit got bigger than ever",
			"I just hopped the jet this shit go straight to LA",
			"Bitch I done got rich I done got richer than ever",
			"Now I got these whips these whips bigger than ever",
			"I been blocking shade I sit under umbrellas",
			"I'm an alien bitch I feel like changing the weather",
			"I don't even talk to nobody no bitch but it's smooth like butter",
			"I been chilling out lil' bitch but I'm high as them devils",
			"We so mad like devils in our head",
			"I'm on demand every time I drop I am",
			"We so mad them devils call me 'Him'",
			"They call me God 'cause I'm as high as Him",
			"I remember back when I was fucking broke",
			"Now I'm chilling out in south of France on a boat",
			"I could make the money come I can make it go",
			"I don't need to fly I just need to flow",
			"I don't even laugh y'all already jokes",
			"All my money flip all my money bloats",
			"All my diamonds shine all my diamonds moats",
			"I might have to go lose control",
			"I got diamonds on my yacht and I got diamonds on my bitch",
			"I could put money on your heads I could put money on your kids",
			"I call the mob and they come kill 'em that's as easy as it gets",
			"I'm done laying back plotting I'm dropping everything I'm dropping all these hits",
			"It take a lot of motherfucking money just to get here and look like this",
			"I had to shit on them constantly so they could look at me and fear for they life",
			"Way back when them thoughts was easy",
			"Now shit get sleazy and it get peezy",
			"I rock APeezy it get fleezy",
			"My diamonds 3D they're not CGI",
			"I can get you dead I can get you fried",
			"I can kill you with no eyes open",
			"They could cut out one of my eyes",
			"Why? Every time I look back they surprised",
			"Now this shit got big this shit got bigger than ever",
			"I just hopped the jet this shit go straight to LA",
			"Bitch I done got rich I done got richer than ever",
			"Now I got these whips these whips bigger than ever",
			"I been blocking shade I sit under umbrellas",
			"I'm an alien bitch I feel like changing the weather",
			"I don't even talk to nobody no bitch but it's smooth like butter",
			"I been chilling out lil' bitch but I'm high as them devils",
			"We so mad like devils in our head",
			"I'm on demand every time I drop I am",
			"We so mad them devils call me 'Him'",
			"They call me God 'cause I'm as high as Him",
			"I remember back when I was fucking broke",
			"Now I'm chilling out in south of France on a boat",
			"I could make the money come I can make it go",
			"I don't need to fly I just need to flow",
			"I don't even laugh y'all already jokes",
			"All my money flip all my money bloats",
			"All my diamonds shine all my diamonds moats",
			"I might have to go lose control",
		],
		songLanguage: "en",
		timings: [
			22, 25, 29, 32, 35, 38, 41, 44, 48, 51, 54, 58, 61, 64, 68, 71, 74, 78,
			81, 84, 90, 96, 103, 109, 114, 122, 125, 128, 131, 135, 138, 142, 144,
			147, 150, 153, 157, 160, 163, 166, 169, 172, 175, 179, 182, 186, 189, 192,
			195, 198, 202, 206, 209,
		],
		end: 248,
		typeOfSong: "K-pop",
		complexity: "HARD",
		image:
			"https://upload.wikimedia.org/wikipedia/en/c/c4/Yeat_-_Bigger_Then_Everything.jpg",
		id: "47832fdkjsdjf10239",
	},
	{
		author: "Yeat",
		title: "Bigger than everything",
		intro: 19,
		lyrics: [
			"Now this shit got big this shit got bigger than ever",
			"I just hopped the jet this shit go straight to LA",
			"Bitch I done got rich I done got richer than ever",
			"Now I got these whips these whips bigger than ever",
			"I been blocking shade I sit under umbrellas",
			"I'm an alien bitch I feel like changing the weather",
			"I don't even talk to nobody no bitch but it's smooth like butter",
			"I been chilling out lil' bitch but I'm high as them devils",
			"We so mad like devils in our head",
			"I'm on demand every time I drop I am",
			"We so mad them devils call me 'Him'",
			"They call me God 'cause I'm as high as Him",
			"I remember back when I was fucking broke",
			"Now I'm chilling out in south of France on a boat",
			"I could make the money come I can make it go",
			"I don't need to fly I just need to flow",
			"I don't even laugh y'all already jokes",
			"All my money flip all my money bloats",
			"All my diamonds shine all my diamonds moats",
			"I might have to go lose control",
			"I got diamonds on my yacht and I got diamonds on my bitch",
			"I could put money on your heads I could put money on your kids",
			"I call the mob and they come kill 'em that's as easy as it gets",
			"I'm done laying back plotting I'm dropping everything I'm dropping all these hits",
			"It take a lot of motherfucking money just to get here and look like this",
			"I had to shit on them constantly so they could look at me and fear for they life",
			"Way back when them thoughts was easy",
			"Now shit get sleazy and it get peezy",
			"I rock APeezy it get fleezy",
			"My diamonds 3D they're not CGI",
			"I can get you dead I can get you fried",
			"I can kill you with no eyes open",
			"They could cut out one of my eyes",
			"Why? Every time I look back they surprised",
			"Now this shit got big this shit got bigger than ever",
			"I just hopped the jet this shit go straight to LA",
			"Bitch I done got rich I done got richer than ever",
			"Now I got these whips these whips bigger than ever",
			"I been blocking shade I sit under umbrellas",
			"I'm an alien bitch I feel like changing the weather",
			"I don't even talk to nobody no bitch but it's smooth like butter",
			"I been chilling out lil' bitch but I'm high as them devils",
			"We so mad like devils in our head",
			"I'm on demand every time I drop I am",
			"We so mad them devils call me 'Him'",
			"They call me God 'cause I'm as high as Him",
			"I remember back when I was fucking broke",
			"Now I'm chilling out in south of France on a boat",
			"I could make the money come I can make it go",
			"I don't need to fly I just need to flow",
			"I don't even laugh y'all already jokes",
			"All my money flip all my money bloats",
			"All my diamonds shine all my diamonds moats",
			"I might have to go lose control",
		],
		songLanguage: "en",
		timings: [
			22, 25, 29, 32, 35, 38, 41, 44, 48, 51, 54, 58, 61, 64, 68, 71, 74, 78,
			81, 84, 90, 96, 103, 109, 114, 122, 125, 128, 131, 135, 138, 142, 144,
			147, 150, 153, 157, 160, 163, 166, 169, 172, 175, 179, 182, 186, 189, 192,
			195, 198, 202, 206, 209,
		],
		end: 248,
		typeOfSong: "Reggie",
		complexity: "HARD",
		image:
			"https://upload.wikimedia.org/wikipedia/en/c/c4/Yeat_-_Bigger_Then_Everything.jpg",
		id: "47832fdkjsdjf10239",
	},
]
